server:
  port: 9010

spring:
  application:
    name: nacos-order
  cloud:
    nacos:
      discovery:
        #配置Nacos地址
        server-addr: 159.75.122.3:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
