server:
  port: 9001
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      # defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      # 单机模式
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    # 优先使用IP而不是其他方式（比如微服务名称）显示
    prefer-ip-address: true
    # 发送心跳的时间间隔
    lease-renewal-interval-in-seconds:  1
    # 服务端等待心跳的最长时间
    lease-expiration-duration-in-seconds:  2
ribbon:
  # 配置Feign的连接时间，默认1秒钟不回复，就会报错
  ReadTimeout:  5000
  # 设置最大连接时间
  ConnectTimeout: 5000
logging:
  level:
    com.example.cloud.order.service.IPaymentService: debug