server:
  port: 10001

eureka:
  client:
    #表识不向注册中心注册自己
    register-with-eureka: true
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

spring:
  application:
    name: cloud-provider-hystrix-payment
  devtools:
    livereload:
      port: 10010

