server:
  port: 7001

eureka:
  instance:
    #eureka服务端的实例名字
    hostname: 127.0.0.1
  client:
    #表示不向注册中心注册自己
    register-with-eureka: false
    #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      # defaultZone: http://127.0.0.1:7002/eureka/
      # 开启单机模式
      defaultZone: http://127.0.0.1:7001/eureka/
  server:
    # 关闭Eureka的保护模式
    enable-self-preservation: false
    # 如果两秒没有发送，那么代表着需要剔除，默认为90秒
    eviction-interval-timer-in-ms: 2000
spring:
  application:
    name: eureka-server
